export const subjects = [
  { name: "English",                image: "https://loremflickr.com/400/300/english,literature,books" },
  { name: "French",                 image: "https://loremflickr.com/400/300/france,paris,eiffel" },
  { name: "Arabic",                 image: "https://loremflickr.com/400/300/arabic,calligraphy,quran" },
  { name: "Biology",                image: "https://loremflickr.com/400/300/biology,microscope,cells" },
  { name: "Mathematics",            image: "https://loremflickr.com/400/300/mathematics,equations,numbers" },
  { name: "Chemistry",              image: "https://loremflickr.com/400/300/chemistry,laboratory,flask" },
  { name: "Physics",                image: "https://loremflickr.com/400/300/physics,space,atoms" },
  { name: "History",                image: "https://loremflickr.com/400/300/history,ancient,ruins" },
  { name: "Geography",              image: "https://loremflickr.com/400/300/geography,map,globe" },
  { name: "Philosophy",             image: "https://loremflickr.com/400/300/philosophy,thinking,ancient" },
  { name: "Economics",              image: "https://loremflickr.com/400/300/economics,finance,money" },
  { name: "Computer Science",       image: "https://loremflickr.com/400/300/computer,programming,code" },
  { name: "Information Technology", image: "https://loremflickr.com/400/300/technology,network,server" },
  { name: "Art",                    image: "https://loremflickr.com/400/300/art,painting,canvas" },
  { name: "Music",                  image: "https://loremflickr.com/400/300/music,instrument,piano" },
  { name: "Physical Education",     image: "https://loremflickr.com/400/300/sports,fitness,running" },
  { name: "Religious Education",    image: "https://loremflickr.com/400/300/religion,church,prayer" },
  { name: "Sociology",              image: "https://loremflickr.com/400/300/sociology,people,community" },
  { name: "Psychology",             image: "https://loremflickr.com/400/300/psychology,brain,mind" },
  { name: "Environmental Science",  image: "https://loremflickr.com/400/300/environment,nature,ecology" },
  { name: "Statistics",             image: "https://loremflickr.com/400/300/statistics,data,charts" },
  { name: "Literature",             image: "https://loremflickr.com/400/300/literature,library,reading" },
  { name: "Drama",                  image: "https://loremflickr.com/400/300/drama,theater,stage" },
  { name: "Design & Technology",    image: "https://loremflickr.com/400/300/design,technology,blueprint" },
  { name: "Business Studies",       image: "https://loremflickr.com/400/300/business,office,corporate" },
  { name: "Vacation",       image: "https://loremflickr.com/400/300/vacation,relax,enjoy" }
];